export default {
  school:[
    {
      id:1,
      schoolName:"남산초등학교",
      grade:1,
      classNumber:1
    },
    {
      id:2,
      schoolName:"남산초등학교",
      grade:1,
      classNumber:2
    },{
      id:3,
      schoolName:"남산초등학교",
      grade:2,
      classNumber:1
    },{
      id:4,
      schoolName:"남산초등학교",
      grade:2,
      classNumber:2
    },{
      id:5,
      schoolName:"동산초등학교",
      grade:1,
      classNumber:1
    },
    {
      id:6,
      schoolName:"동산초등학교",
      grade:1,
      classNumber:2
    },{
      id:7,
      schoolName:"동산초등학교",
      grade:2,
      classNumber:1
    },{
      id:8,
      schoolName:"동산초등학교",
      grade:2,
      classNumber:2
    }
  ],
  user:[
    {
      id:1,
      name:"김선생",
      school:{
        id:1,
        schoolName:"남산초등학교",
        grade:1,
        classNumber:1
      },
      type:"teacher"
    },
    {
      id:1,
      name:"이선생",
      school:{
        id:1,
        grade:1,
        classNumber:1
      },
      type:"teacher"
    }
  ],
  supplyAndLeft:[
    {
    // 2019년 8월 12일
      id:1,
      userId:1,
      user:{
        name:"홍길동",
        school:{
          id:1,
          schoolName:"남산초등학교",
          grade:1,
          classNumber:1
        },
        type:"student"
      },
      Date: new Date(2019,7,12),
      food1_id:1,
      food1:{
        id:1,
        name:"쌀밥",
        from:"국내산",
        allergy:false,
        special:null
      },
      food1_supply:300,
      food1_left:100,
      food2_id:2,
      food2:{
        id:2,
        name:"된장3",
        from:"국내산",
        allergy:false,
        special:null
      },
      food2_supply:500,
      food2_left:100,
      food3_id:3,
      food3:{
        id:3,
        name:"불고기",
        from:"국내산",
        allergy:false,
        special:null
      },
      food3_supply:200,
      food3_left:30,
      food4_id:4,
      food4:{
        id:4,
        name:"김치",
        from:"국내산",
        allergy:false,
        special:null
      },
      food4_supply:300,
      food4_left:200,
      food5_id:5,
      food5:{
        id:5,
        name:"멸치볶음",
        from:"국내산",
        allergy:false,
        special:null
      },
      food5_supply:100,
      food5_left:10,
      food6_id:6,
      food6:{
        id:6,
        name:"토마토",
        from:"국내산",
        allergy:true,
        special:null
      },
      food6_supply:100,
      food6_left:10,
    },

    {
      id:2,
      userId:2,
      user:{
        name:"이순신",
        school:{
          id:2,
          schoolName:"남산초등학교",
          grade:1,
          classNumber:2
        },
        type:"student"
      },
      Date: new Date(2019,7,12),
      food1_id:1,
      food1:{
        id:1,
        name:"쌀밥",
        from:"국내산",
        allergy:false,
        special:null
      },
      food1_supply:300,
      food1_left:100,
      food2_id:2,
      food2:{
        id:2,
        name:"된장3",
        from:"국내산",
        allergy:false,
        special:null
      },
      food2_supply:500,
      food2_left:100,
      food3_id:3,
      food3:{
        id:3,
        name:"불고기",
        from:"국내산",
        allergy:false,
        special:null
      },
      food3_supply:200,
      food3_left:30,
      food4_id:4,
      food4:{
        id:4,
        name:"김치",
        from:"국내산",
        allergy:false,
        special:null
      },
      food4_supply:300,
      food4_left:200,
      food5_id:5,
      food5:{
        id:5,
        name:"멸치볶음",
        from:"국내산",
        allergy:false,
        special:null
      },
      food5_supply:100,
      food5_left:10,
      food6_id:6,
      food6:{
        id:6,
        name:"토마토",
        from:"국내산",
        allergy:true,
        special:null
      },
      food6_supply:100,
      food6_left:10,
    },

    {
      id:3,
      userId:3,
      user:{
        name:"곽재우",
        school:{
          id:3,
          schoolName:"남산초등학교",
          grade:2,
          classNumber:1
        },
        type:"student"
      },
      Date: new Date(2019,7,12),
      food1_id:1,
      food1:{
        id:1,
        name:"쌀밥",
        from:"국내산",
        allergy:false,
        special:null
      },
      food1_supply:300,
      food1_left:100,
      food2_id:2,
      food2:{
        id:2,
        name:"된장3",
        from:"국내산",
        allergy:false,
        special:null
      },
      food2_supply:500,
      food2_left:100,
      food3_id:3,
      food3:{
        id:3,
        name:"불고기",
        from:"국내산",
        allergy:false,
        special:null
      },
      food3_supply:200,
      food3_left:30,
      food4_id:4,
      food4:{
        id:4,
        name:"김치",
        from:"국내산",
        allergy:false,
        special:null
      },
      food4_supply:300,
      food4_left:200,
      food5_id:5,
      food5:{
        id:5,
        name:"멸치볶음",
        from:"국내산",
        allergy:false,
        special:null
      },
      food5_supply:100,
      food5_left:10,
      food6_id:6,
      food6:{
        id:6,
        name:"토마토",
        from:"국내산",
        allergy:true,
        special:null
      },
      food6_supply:100,
      food6_left:10,
    },

    {
      id:4,
      userId:4,
      user:{
        name:"김세종",
        school:{
          id:3,
          schoolName:"남산초등학교",
          grade:2,
          classNumber:1
        },
        type:"student"
      },
      Date: new Date(2019,7,12),
      food1_id:1,
      food1:{
        id:1,
        name:"쌀밥",
        from:"국내산",
        allergy:false,
        special:null
      },
      food1_supply:300,
      food1_left:100,
      food2_id:2,
      food2:{
        id:2,
        name:"된장3",
        from:"국내산",
        allergy:false,
        special:null
      },
      food2_supply:500,
      food2_left:100,
      food3_id:3,
      food3:{
        id:3,
        name:"불고기",
        from:"국내산",
        allergy:false,
        special:null
      },
      food3_supply:200,
      food3_left:30,
      food4_id:4,
      food4:{
        id:4,
        name:"김치",
        from:"국내산",
        allergy:false,
        special:null
      },
      food4_supply:300,
      food4_left:200,
      food5_id:5,
      food5:{
        id:5,
        name:"멸치볶음",
        from:"국내산",
        allergy:false,
        special:null
      },
      food5_supply:100,
      food5_left:10,
      food6_id:6,
      food6:{
        id:6,
        name:"토마토",
        from:"국내산",
        allergy:true,
        special:null
      },
      food6_supply:100,
      food6_left:10,
    },

    {
      id:5,
      userId:5,
      user:{
        name:"김태종",
        school:{
          id:4,
          schoolName:"남산초등학교",
          grade:2,
          classNumber:2
        },
        type:"student"
      },
      Date: new Date(2019,7,12),
      food1_id:1,
      food1:{
        id:1,
        name:"쌀밥",
        from:"국내산",
        allergy:false,
        special:null
      },
      food1_supply:300,
      food1_left:100,
      food2_id:2,
      food2:{
        id:2,
        name:"된장3",
        from:"국내산",
        allergy:false,
        special:null
      },
      food2_supply:500,
      food2_left:100,
      food3_id:3,
      food3:{
        id:3,
        name:"불고기",
        from:"국내산",
        allergy:false,
        special:null
      },
      food3_supply:200,
      food3_left:30,
      food4_id:4,
      food4:{
        id:4,
        name:"김치",
        from:"국내산",
        allergy:false,
        special:null
      },
      food4_supply:300,
      food4_left:200,
      food5_id:5,
      food5:{
        id:5,
        name:"멸치볶음",
        from:"국내산",
        allergy:false,
        special:null
      },
      food5_supply:100,
      food5_left:10,
      food6_id:6,
      food6:{
        id:6,
        name:"토마토",
        from:"국내산",
        allergy:true,
        special:null
      },
      food6_supply:100,
      food6_left:10,
    },

    {
      id:6,
      userId:6,
      user:{
        name:"김정종",
        school:{
          id:5,
          schoolName:"동산초등학교",
          grade:1,
          classNumber:1
        },
        type:"student"
      },
      Date: new Date(2019,7,12),
      food1_id:1,
      food1:{
        id:1,
        name:"쌀밥",
        from:"국내산",
        allergy:false,
        special:null
      },
      food1_supply:300,
      food1_left:100,
      food2_id:2,
      food2:{
        id:2,
        name:"된장3",
        from:"국내산",
        allergy:false,
        special:null
      },
      food2_supply:500,
      food2_left:100,
      food3_id:3,
      food3:{
        id:3,
        name:"불고기",
        from:"국내산",
        allergy:false,
        special:null
      },
      food3_supply:200,
      food3_left:30,
      food4_id:4,
      food4:{
        id:4,
        name:"김치",
        from:"국내산",
        allergy:false,
        special:null
      },
      food4_supply:300,
      food4_left:200,
      food5_id:5,
      food5:{
        id:5,
        name:"멸치볶음",
        from:"국내산",
        allergy:false,
        special:null
      },
      food5_supply:100,
      food5_left:10,
      food6_id:6,
      food6:{
        id:6,
        name:"토마토",
        from:"국내산",
        allergy:true,
        special:null
      },
      food6_supply:100,
      food6_left:10,
    },

    {
      id:7,
      userId:7,
      user:{
        name:"김문종",
        school:{
          id:5,
          schoolName:"동산초등학교",
          grade:1,
          classNumber:1
        },
        type:"student"
      },
      Date: new Date(2019,7,12),
      food1_id:1,
      food1:{
        id:1,
        name:"쌀밥",
        from:"국내산",
        allergy:false,
        special:null
      },
      food1_supply:300,
      food1_left:100,
      food2_id:2,
      food2:{
        id:2,
        name:"된장3",
        from:"국내산",
        allergy:false,
        special:null
      },
      food2_supply:500,
      food2_left:100,
      food3_id:3,
      food3:{
        id:3,
        name:"불고기",
        from:"국내산",
        allergy:false,
        special:null
      },
      food3_supply:200,
      food3_left:30,
      food4_id:4,
      food4:{
        id:4,
        name:"김치",
        from:"국내산",
        allergy:false,
        special:null
      },
      food4_supply:300,
      food4_left:200,
      food5_id:5,
      food5:{
        id:5,
        name:"멸치볶음",
        from:"국내산",
        allergy:false,
        special:null
      },
      food5_supply:100,
      food5_left:10,
      food6_id:6,
      food6:{
        id:6,
        name:"토마토",
        from:"국내산",
        allergy:true,
        special:null
      },
      food6_supply:100,
      food6_left:10,
    },

    {
      id:8,
      userId:8,
      user:{
        name:"김예종",
        school:{
          id:6,
          schoolName:"동산초등학교",
          grade:1,
          classNumber:2
        },
        type:"student"
      },
      Date: new Date(2019,7,12),
      food1_id:1,
      food1:{
        id:1,
        name:"쌀밥",
        from:"국내산",
        allergy:false,
        special:null
      },
      food1_supply:300,
      food1_left:100,
      food2_id:2,
      food2:{
        id:2,
        name:"된장3",
        from:"국내산",
        allergy:false,
        special:null
      },
      food2_supply:500,
      food2_left:100,
      food3_id:3,
      food3:{
        id:3,
        name:"불고기",
        from:"국내산",
        allergy:false,
        special:null
      },
      food3_supply:200,
      food3_left:30,
      food4_id:4,
      food4:{
        id:4,
        name:"김치",
        from:"국내산",
        allergy:false,
        special:null
      },
      food4_supply:300,
      food4_left:200,
      food5_id:5,
      food5:{
        id:5,
        name:"멸치볶음",
        from:"국내산",
        allergy:false,
        special:null
      },
      food5_supply:100,
      food5_left:10,
      food6_id:6,
      food6:{
        id:6,
        name:"토마토",
        from:"국내산",
        allergy:true,
        special:null
      },
      food6_supply:100,
      food6_left:10,
    },

    {
      id:9,
      userId:9,
      user:{
        name:"홍범도",
        school:{
          id:7,
          schoolName:"동산초등학교",
          grade:2,
          classNumber:1
        },
        type:"student"
      },
      Date: new Date(2019,7,12),
      food1_id:1,
      food1:{
        id:1,
        name:"쌀밥",
        from:"국내산",
        allergy:false,
        special:null
      },
      food1_supply:300,
      food1_left:100,
      food2_id:2,
      food2:{
        id:2,
        name:"된장3",
        from:"국내산",
        allergy:false,
        special:null
      },
      food2_supply:500,
      food2_left:100,
      food3_id:3,
      food3:{
        id:3,
        name:"불고기",
        from:"국내산",
        allergy:false,
        special:null
      },
      food3_supply:200,
      food3_left:30,
      food4_id:4,
      food4:{
        id:4,
        name:"김치",
        from:"국내산",
        allergy:false,
        special:null
      },
      food4_supply:300,
      food4_left:200,
      food5_id:5,
      food5:{
        id:5,
        name:"멸치볶음",
        from:"국내산",
        allergy:false,
        special:null
      },
      food5_supply:100,
      food5_left:10,
      food6_id:6,
      food6:{
        id:6,
        name:"토마토",
        from:"국내산",
        allergy:true,
        special:null
      },
      food6_supply:100,
      food6_left:10,
    },

    {
      id:10,
      userId:10,
      user:{
        name:"김철수",
        school:{
          id:8,
          schoolName:"동산초등학교",
          grade:2,
          classNumber:2
        },
        type:"student"
      },
      Date: new Date(2019,7,12),
      food1_id:1,
      food1:{
        id:1,
        name:"쌀밥",
        from:"국내산",
        allergy:false,
        special:null
      },
      food1_supply:300,
      food1_left:100,
      food2_id:2,
      food2:{
        id:2,
        name:"된장3",
        from:"국내산",
        allergy:false,
        special:null
      },
      food2_supply:500,
      food2_left:100,
      food3_id:3,
      food3:{
        id:3,
        name:"불고기",
        from:"국내산",
        allergy:false,
        special:null
      },
      food3_supply:200,
      food3_left:30,
      food4_id:4,
      food4:{
        id:4,
        name:"김치",
        from:"국내산",
        allergy:false,
        special:null
      },
      food4_supply:300,
      food4_left:200,
      food5_id:5,
      food5:{
        id:5,
        name:"멸치볶음",
        from:"국내산",
        allergy:false,
        special:null
      },
      food5_supply:100,
      food5_left:10,
      food6_id:6,
      food6:{
        id:6,
        name:"토마토",
        from:"국내산",
        allergy:true,
        special:null
      },
      food6_supply:100,
      food6_left:10,
    },


    // 2019년 8월 13일
    {
      id:11,
      userId:1,
      user:{
        name:"홍길동",
        school:{
          id:1,
          schoolName:"남산초등학교",
          grade:1,
          classNumber:1
        },
        type:"student"
      },
      Date: new Date(2019,7,13),
      food1_id:1,
      food1:{
        id:1,
        name:"쌀밥",
        from:"국내산",
        allergy:false,
        special:null
      },
      food1_supply:300,
      food1_left:100,
      food2_id:2,
      food2:{
        id:2,
        name:"된장3",
        from:"국내산",
        allergy:false,
        special:null
      },
      food2_supply:500,
      food2_left:100,
      food3_id:3,
      food3:{
        id:3,
        name:"불고기",
        from:"국내산",
        allergy:false,
        special:null
      },
      food3_supply:200,
      food3_left:30,
      food4_id:4,
      food4:{
        id:4,
        name:"김치",
        from:"국내산",
        allergy:false,
        special:null
      },
      food4_supply:300,
      food4_left:200,
      food5_id:5,
      food5:{
        id:5,
        name:"멸치볶음",
        from:"국내산",
        allergy:false,
        special:null
      },
      food5_supply:100,
      food5_left:10,
      food6_id:6,
      food6:{
        id:6,
        name:"토마토",
        from:"국내산",
        allergy:true,
        special:null
      },
      food6_supply:100,
      food6_left:10,
    },

    {
      id:12,
      userId:2,
      user:{
        name:"이순신",
        school:{
          id:2,
          schoolName:"남산초등학교",
          grade:1,
          classNumber:2
        },
        type:"student"
      },
      Date: new Date(2019,7,13),
      food1_id:1,
      food1:{
        id:1,
        name:"쌀밥",
        from:"국내산",
        allergy:false,
        special:null
      },
      food1_supply:300,
      food1_left:100,
      food2_id:2,
      food2:{
        id:2,
        name:"된장3",
        from:"국내산",
        allergy:false,
        special:null
      },
      food2_supply:500,
      food2_left:100,
      food3_id:3,
      food3:{
        id:3,
        name:"불고기",
        from:"국내산",
        allergy:false,
        special:null
      },
      food3_supply:200,
      food3_left:30,
      food4_id:4,
      food4:{
        id:4,
        name:"김치",
        from:"국내산",
        allergy:false,
        special:null
      },
      food4_supply:300,
      food4_left:200,
      food5_id:5,
      food5:{
        id:5,
        name:"멸치볶음",
        from:"국내산",
        allergy:false,
        special:null
      },
      food5_supply:100,
      food5_left:10,
      food6_id:6,
      food6:{
        id:6,
        name:"토마토",
        from:"국내산",
        allergy:true,
        special:null
      },
      food6_supply:100,
      food6_left:10,
    },

    {
      id:13,
      userId:3,
      user:{
        name:"곽재우",
        school:{
          id:3,
          schoolName:"남산초등학교",
          grade:2,
          classNumber:1
        },
        type:"student"
      },
      Date: new Date(2019,7,13),
      food1_id:1,
      food1:{
        id:1,
        name:"쌀밥",
        from:"국내산",
        allergy:false,
        special:null
      },
      food1_supply:300,
      food1_left:100,
      food2_id:2,
      food2:{
        id:2,
        name:"된장3",
        from:"국내산",
        allergy:false,
        special:null
      },
      food2_supply:500,
      food2_left:100,
      food3_id:3,
      food3:{
        id:3,
        name:"불고기",
        from:"국내산",
        allergy:false,
        special:null
      },
      food3_supply:200,
      food3_left:30,
      food4_id:4,
      food4:{
        id:4,
        name:"김치",
        from:"국내산",
        allergy:false,
        special:null
      },
      food4_supply:300,
      food4_left:200,
      food5_id:5,
      food5:{
        id:5,
        name:"멸치볶음",
        from:"국내산",
        allergy:false,
        special:null
      },
      food5_supply:100,
      food5_left:10,
      food6_id:6,
      food6:{
        id:6,
        name:"토마토",
        from:"국내산",
        allergy:true,
        special:null
      },
      food6_supply:100,
      food6_left:10,
    },

    {
      id:14,
      userId:4,
      user:{
        name:"김세종",
        school:{
          id:3,
          schoolName:"남산초등학교",
          grade:2,
          classNumber:1
        },
        type:"student"
      },
      Date: new Date(2019,7,13),
      food1_id:1,
      food1:{
        id:1,
        name:"쌀밥",
        from:"국내산",
        allergy:false,
        special:null
      },
      food1_supply:300,
      food1_left:100,
      food2_id:2,
      food2:{
        id:2,
        name:"된장3",
        from:"국내산",
        allergy:false,
        special:null
      },
      food2_supply:500,
      food2_left:100,
      food3_id:3,
      food3:{
        id:3,
        name:"불고기",
        from:"국내산",
        allergy:false,
        special:null
      },
      food3_supply:200,
      food3_left:30,
      food4_id:4,
      food4:{
        id:4,
        name:"김치",
        from:"국내산",
        allergy:false,
        special:null
      },
      food4_supply:300,
      food4_left:200,
      food5_id:5,
      food5:{
        id:5,
        name:"멸치볶음",
        from:"국내산",
        allergy:false,
        special:null
      },
      food5_supply:100,
      food5_left:10,
      food6_id:6,
      food6:{
        id:6,
        name:"토마토",
        from:"국내산",
        allergy:true,
        special:null
      },
      food6_supply:100,
      food6_left:10,
    },

    {
      id:15,
      userId:5,
      user:{
        name:"김태종",
        school:{
          id:4,
          schoolName:"남산초등학교",
          grade:2,
          classNumber:2
        },
        type:"student"
      },
      Date: new Date(2019,7,13),
      food1_id:1,
      food1:{
        id:1,
        name:"쌀밥",
        from:"국내산",
        allergy:false,
        special:null
      },
      food1_supply:300,
      food1_left:100,
      food2_id:2,
      food2:{
        id:2,
        name:"된장3",
        from:"국내산",
        allergy:false,
        special:null
      },
      food2_supply:500,
      food2_left:100,
      food3_id:3,
      food3:{
        id:3,
        name:"불고기",
        from:"국내산",
        allergy:false,
        special:null
      },
      food3_supply:200,
      food3_left:30,
      food4_id:4,
      food4:{
        id:4,
        name:"김치",
        from:"국내산",
        allergy:false,
        special:null
      },
      food4_supply:300,
      food4_left:200,
      food5_id:5,
      food5:{
        id:5,
        name:"멸치볶음",
        from:"국내산",
        allergy:false,
        special:null
      },
      food5_supply:100,
      food5_left:10,
      food6_id:6,
      food6:{
        id:6,
        name:"토마토",
        from:"국내산",
        allergy:true,
        special:null
      },
      food6_supply:100,
      food6_left:10,
    },

    {
      id:16,
      userId:6,
      user:{
        name:"김정종",
        school:{
          id:5,
          schoolName:"동산초등학교",
          grade:1,
          classNumber:1
        },
        type:"student"
      },
      Date: new Date(2019,7,13),
      food1_id:1,
      food1:{
        id:1,
        name:"쌀밥",
        from:"국내산",
        allergy:false,
        special:null
      },
      food1_supply:300,
      food1_left:100,
      food2_id:2,
      food2:{
        id:2,
        name:"된장3",
        from:"국내산",
        allergy:false,
        special:null
      },
      food2_supply:500,
      food2_left:100,
      food3_id:3,
      food3:{
        id:3,
        name:"불고기",
        from:"국내산",
        allergy:false,
        special:null
      },
      food3_supply:200,
      food3_left:30,
      food4_id:4,
      food4:{
        id:4,
        name:"김치",
        from:"국내산",
        allergy:false,
        special:null
      },
      food4_supply:300,
      food4_left:200,
      food5_id:5,
      food5:{
        id:5,
        name:"멸치볶음",
        from:"국내산",
        allergy:false,
        special:null
      },
      food5_supply:100,
      food5_left:10,
      food6_id:6,
      food6:{
        id:6,
        name:"토마토",
        from:"국내산",
        allergy:true,
        special:null
      },
      food6_supply:100,
      food6_left:10,
    },

    {
      id:17,
      userId:7,
      user:{
        name:"김문종",
        school:{
          id:5,
          schoolName:"동산초등학교",
          grade:1,
          classNumber:1
        },
        type:"student"
      },
      Date: new Date(2019,7,13),
      food1_id:1,
      food1:{
        id:1,
        name:"쌀밥",
        from:"국내산",
        allergy:false,
        special:null
      },
      food1_supply:300,
      food1_left:100,
      food2_id:2,
      food2:{
        id:2,
        name:"된장3",
        from:"국내산",
        allergy:false,
        special:null
      },
      food2_supply:500,
      food2_left:100,
      food3_id:3,
      food3:{
        id:3,
        name:"불고기",
        from:"국내산",
        allergy:false,
        special:null
      },
      food3_supply:200,
      food3_left:30,
      food4_id:4,
      food4:{
        id:4,
        name:"김치",
        from:"국내산",
        allergy:false,
        special:null
      },
      food4_supply:300,
      food4_left:200,
      food5_id:5,
      food5:{
        id:5,
        name:"멸치볶음",
        from:"국내산",
        allergy:false,
        special:null
      },
      food5_supply:100,
      food5_left:10,
      food6_id:6,
      food6:{
        id:6,
        name:"토마토",
        from:"국내산",
        allergy:true,
        special:null
      },
      food6_supply:100,
      food6_left:10,
    },

    {
      id:18,
      userId:8,
      user:{
        name:"김예종",
        school:{
          id:6,
          schoolName:"동산초등학교",
          grade:1,
          classNumber:2
        },
        type:"student"
      },
      Date: new Date(2019,7,13),
      food1_id:1,
      food1:{
        id:1,
        name:"쌀밥",
        from:"국내산",
        allergy:false,
        special:null
      },
      food1_supply:300,
      food1_left:100,
      food2_id:2,
      food2:{
        id:2,
        name:"된장3",
        from:"국내산",
        allergy:false,
        special:null
      },
      food2_supply:500,
      food2_left:100,
      food3_id:3,
      food3:{
        id:3,
        name:"불고기",
        from:"국내산",
        allergy:false,
        special:null
      },
      food3_supply:200,
      food3_left:30,
      food4_id:4,
      food4:{
        id:4,
        name:"김치",
        from:"국내산",
        allergy:false,
        special:null
      },
      food4_supply:300,
      food4_left:200,
      food5_id:5,
      food5:{
        id:5,
        name:"멸치볶음",
        from:"국내산",
        allergy:false,
        special:null
      },
      food5_supply:100,
      food5_left:10,
      food6_id:6,
      food6:{
        id:6,
        name:"토마토",
        from:"국내산",
        allergy:true,
        special:null
      },
      food6_supply:100,
      food6_left:10,
    },

    {
      id:19,
      userId:9,
      user:{
        name:"홍범도",
        school:{
          id:7,
          schoolName:"동산초등학교",
          grade:2,
          classNumber:1
        },
        type:"student"
      },
      Date: new Date(2019,7,13),
      food1_id:1,
      food1:{
        id:1,
        name:"쌀밥",
        from:"국내산",
        allergy:false,
        special:null
      },
      food1_supply:300,
      food1_left:100,
      food2_id:2,
      food2:{
        id:2,
        name:"된장3",
        from:"국내산",
        allergy:false,
        special:null
      },
      food2_supply:500,
      food2_left:100,
      food3_id:3,
      food3:{
        id:3,
        name:"불고기",
        from:"국내산",
        allergy:false,
        special:null
      },
      food3_supply:200,
      food3_left:30,
      food4_id:4,
      food4:{
        id:4,
        name:"김치",
        from:"국내산",
        allergy:false,
        special:null
      },
      food4_supply:300,
      food4_left:200,
      food5_id:5,
      food5:{
        id:5,
        name:"멸치볶음",
        from:"국내산",
        allergy:false,
        special:null
      },
      food5_supply:100,
      food5_left:10,
      food6_id:6,
      food6:{
        id:6,
        name:"토마토",
        from:"국내산",
        allergy:true,
        special:null
      },
      food6_supply:100,
      food6_left:10,
    },

    {
      id:20,
      userId:10,
      user:{
        name:"김철수",
        school:{
          id:8,
          schoolschoolName:"동산초등학교",
          grade:2,
          classNumber:2
        },
        type:"student"
      },
      Date: new Date(2019,7,13),
      food1_id:1,
      food1:{
        id:1,
        name:"쌀밥",
        from:"국내산",
        allergy:false,
        special:null
      },
      food1_supply:300,
      food1_left:100,
      food2_id:2,
      food2:{
        id:2,
        name:"된장3",
        from:"국내산",
        allergy:false,
        special:null
      },
      food2_supply:500,
      food2_left:100,
      food3_id:3,
      food3:{
        id:3,
        name:"불고기",
        from:"국내산",
        allergy:false,
        special:null
      },
      food3_supply:200,
      food3_left:30,
      food4_id:4,
      food4:{
        id:4,
        name:"김치",
        from:"국내산",
        allergy:false,
        special:null
      },
      food4_supply:300,
      food4_left:200,
      food5_id:5,
      food5:{
        id:5,
        name:"멸치볶음",
        from:"국내산",
        allergy:false,
        special:null
      },
      food5_supply:100,
      food5_left:10,
      food6_id:6,
      food6:{
        id:6,
        name:"토마토",
        from:"국내산",
        allergy:true,
        special:null
      },
      food6_supply:100,
      food6_left:10,
    }
  ]
}
